# Publish all joint states -----------------------------------
joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50  

# Effort Controllers ---------------------------------------
#LH1
propeller_LH1_torque_controller:
     type: effort_controllers/JointEffortController
     joint: LH1_spin
     pid: {p: 0, i: 0, d: 0}

#LH2
propeller_LH2_torque_controller:
     type: effort_controllers/JointEffortController
     joint: LH2_spin
     pid: {p: 0, i: 0, d: 0}

#LH3
propeller_LH3_torque_controller:
     type: effort_controllers/JointEffortController
     joint: LH3_spin
     pid: {p: 0, i: 0, d: 0}

#RH1
propeller_RH1_torque_controller:
    type: effort_controllers/JointEffortController
    joint: RH1_spin
    pid: {p: 0, i: 0, d: 0}

#RH2
propeller_RH2_torque_controller:
    type: effort_controllers/JointEffortController
    joint: RH2_spin
    pid: {p: 0, i: 0, d: 0}

#RH3
propeller_RH3_torque_controller:
    type: effort_controllers/JointEffortController
    joint: RH3_spin
    pid: {p: 0, i: 0, d: 0}
